function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function formatDate(date) {
  return new Intl.DateTimeFormat("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "UTC"
  }).format(date);
}

function renderMessage(message) {
  const author = escapeHtml(message.author?.tag || message.author?.username || "Unknown user");
  const avatar = message.author?.displayAvatarURL?.({ extension: "png", size: 64 }) || "";
  const content = escapeHtml(message.content || "").replaceAll("\n", "<br>");
  const attachments = [...message.attachments.values()]
    .map(
      (attachment) =>
        `<li><a href="${escapeHtml(attachment.url)}" target="_blank" rel="noreferrer">${escapeHtml(attachment.name || attachment.url)}</a></li>`
    )
    .join("");
  const attachmentBlock = attachments ? `<ul class="attachments">${attachments}</ul>` : "";

  return `
    <article class="message">
      <img class="avatar" src="${escapeHtml(avatar)}" alt="">
      <div class="message-body">
        <div class="message-meta"><strong>${author}</strong><time>${escapeHtml(formatDate(message.createdAt))}</time></div>
        <div class="message-content">${content || "<em>No text content</em>"}${attachmentBlock}</div>
      </div>
    </article>`;
}

function buildTranscript({ channel, guild, messages, closedBy, reason }) {
  const sorted = [...messages].sort((a, b) => a.createdTimestamp - b.createdTimestamp);
  const title = `Ticket Transcript — ${channel.name}`;
  const guildName = escapeHtml(guild?.name || "Unknown server");
  const closer = escapeHtml(closedBy?.tag || closedBy?.username || "Unknown staff member");
  const messageMarkup = sorted.map(renderMessage).join("\n");

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { color-scheme: dark; --bg: #09090d; --panel: #13131a; --line: #292936; --accent: #7657ff; --muted: #a7a6b5; }
    * { box-sizing: border-box; }
    body { margin: 0; background: radial-gradient(circle at 15% 0%, #17132b 0, var(--bg) 42%); color: #f4f3f8; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }
    .shell { width: min(100% - 32px, 980px); margin: 32px auto; }
    .hero, .message { background: rgba(19, 19, 26, .94); border: 1px solid var(--line); border-radius: 18px; box-shadow: 0 14px 50px rgba(0, 0, 0, .22); }
    .hero { padding: 28px; border-top: 3px solid var(--accent); margin-bottom: 18px; }
    h1 { margin: 0 0 10px; font-size: clamp(24px, 4vw, 36px); }
    .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 10px; margin-top: 20px; }
    .stat { padding: 13px 15px; background: #1a1a23; border-radius: 12px; color: var(--muted); font-size: 12px; }
    .stat strong { display: block; color: #fff; margin-top: 5px; font-size: 14px; word-break: break-word; }
    .messages { display: grid; gap: 10px; }
    .message { display: flex; gap: 13px; padding: 15px 17px; }
    .avatar { width: 38px; height: 38px; border-radius: 50%; object-fit: cover; background: #292936; flex: 0 0 auto; }
    .message-body { min-width: 0; flex: 1; }
    .message-meta { display: flex; align-items: baseline; gap: 10px; flex-wrap: wrap; }
    .message-meta time { color: var(--muted); font-size: 12px; }
    .message-content { color: #dedde6; margin-top: 7px; line-height: 1.55; overflow-wrap: anywhere; }
    .message-content em { color: var(--muted); }
    .attachments { margin: 9px 0 0; padding-left: 18px; }
    a { color: #9f8fff; }
    .empty { padding: 30px; text-align: center; color: var(--muted); }
    footer { color: var(--muted); text-align: center; font-size: 12px; padding: 20px; }
  </style>
</head>
<body>
  <main class="shell">
    <header class="hero">
      <h1>${escapeHtml(title)}</h1>
      <div class="summary">
        <div class="stat">Server<strong>${guildName}</strong></div>
        <div class="stat">Channel<strong>#${escapeHtml(channel.name)}</strong></div>
        <div class="stat">Closed by<strong>${closer}</strong></div>
        <div class="stat">Reason<strong>${escapeHtml(reason || "No reason provided")}</strong></div>
      </div>
    </header>
    <section class="messages">${messageMarkup || '<div class="hero empty">No messages were found in this ticket.</div>'}</section>
    <footer>Generated by ZYRE MC Ticket Desk • ${escapeHtml(formatDate(new Date()))} UTC</footer>
  </main>
</body>
</html>`;
}

module.exports = { buildTranscript };